### ISSUE TITLE
Compute_surf nflux and mflux are not calculated as intended

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#361]
## Summary

Compute_surf nflux and mflux are not calculated as intended. If using a non-transparent surface, the calculation for flux and flux without any surface reaction will always return a zero value. I do not believe that is the correct behavior, nor definition of a number flux (and by extension a mass flux). The number flux definition from both Bird 94/14, and Boyd/Schwartzentruber 17, is simply a sum over all the impacting molecules. There should not be any subtraction for reflected molecules, or any effect due to surface chemistry.

## Type of Issue

Bug Report

## SPARTA Version

Current master

## Expected Behavior

A number flux (or mass flux) should be related the "num" variable, and simply be "num" scaled by the surface area, time step and Fnum. No subtraction for reflected particles.

## Current code and proposed new code

https://github.com/sparta/sparta/blob/76be34cf06187b525065a3c547b3b04d11944702/src/compute_surf.cpp#L325

    case NFLUX:
      vec[k] += weight * fluxscale;
      if (!transparent) {
        if (ip) vec[k] -= weight * fluxscale;
        if (jp) vec[k] -= weight * fluxscale;
      }
      k++;
      break;
    case MFLUX:
      vec[k] += origmass * fluxscale;
      if (!transparent) {
        if (ip) vec[k] -= imass * fluxscale;
        if (jp) vec[k] -= jmass * fluxscale;
      }
      k++;
      break;

The "if (!transparent)" statement is not appropriate and should be removed. Only the "vec[k] += weight * fluxscale;" line should be present, i.e., I believe the correct code should be:

    case NFLUX:
      vec[k++] += weight * fluxscale;
      break;
    case MFLUX:
      vec[k++] += origmass * fluxscale;
      break;

**Comment by timteichmann** [comment]
Physically speaking the current behavior is correct: flux is defined as flow rate by area. If the surface is closed and all particles are reflected the flux and the flow rate thru the surf should be zero. The same definition is also used in Bird 94, see equation 7.45, where

`Ndot = Ndot_incident + Ndot_reflected = 0`

I can imagine that this is not very useful for external flows (e.g. a particle stream interacting with a sphere), where you would probably be interested in the incident flux alone. However, for internal flows (particles flying inside a structure and coming in and out through surfaces) the current definition is very useful, especially if you have porous walls. Since I am mostly working with internal flows I wanted to provide the explanation why I am in favor of the current implementation ;-)

The individual fluxes of incident and reflected particles can be computed using two transparent surfaces with opposite normals.

**Comment by stanmoore1** [comment]
@aborner1 @timteichmann is there a consensus on this issue? i.e. should we add `nflux_incident` and `mflux_incident`?

**Comment by aborner1** [comment]
@stanmoore1 I think we have agreed to disagree here. It's all a matter of the definition of these quantities. To me, the command is not useful as is, but I also understand it's would not be useful to Tim, were it the way I suggested it.

**Comment by stanmoore1** [comment]
@aborner1 would adding nflux_incident and mflux_incident be useful?

**Comment by aborner1** [comment]
From my perspective, totally

**Comment by timteichmann** [comment]
@stanmoore1 @aborner1 from my perspective this would also be the perfect solution.

**Comment by stanmoore1** [comment]
@timteichmann sorry for the delay--if you have time to submit a PR that would be really helpful.
