### ISSUE TITLE
Move/Surf

### ISSUE THREAD

**Issue by oscillatingion** [sparta/sparta#399]
## Summary

In the input script of "in.surf.rotate," why is the number of nscoll  greatly reduced when the surface starts to rotate (fix 10), even without using scale in the read_surf command?  Could you please provide some explanation for me?   Thank you for your help!   

https://github.com/sparta/sparta/blob/master/examples/surf/in.surf.rotate

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

26 Feb 2021

**Comment by stanmoore1** [comment]
@oscillatingion, I talked to @sjplimp and he pointed out this note from the doc page (see https://sparta.github.io/doc/move_surf.html):

```
After the surface has been moved, then all particles in grid cells that meet either of these criteria are deleted:

the grid cell is now inside a surface
the grid cell overlaps with a surface element that moved
This is to prevent particles from ending up inside surface objects.
```

So this fix is intended to adjust the surface and then allow for re-equilibration of the flow after a few timesteps. It currently won't "bounce" particles off the moving surface and impart momentum to the particles.

There may be a way to take some of the logic from #381 and apply it to the moving surface so only the particles that actually overlap with the surface are deleted, instead of all the particles in any grid cell that overlaps with a surface.

There may also be a way to couple a moving surface with the particles so they do bounce off the moving surface, but that would require modifications to the code.

Can you clarify your intended use case and what you need here?

**Comment by sjplimp** [comment]
Charles - sorry, I'm still not clear on what you are asking for.

a) Do you mean moving/spinning in the sense that a wall surface is sliding
tangentially (e.g. for Couette flow)
    of a circle (in 2d) is spinning around its center point?  If so, then
the surf_collide command
    with its translate or rotate options can produce that effect.  So that
the post-collide velocities of particles which collide with
    the surface account for the effect of the translating/rotating
surface.  In this scenario, the surface itself (e.g. triangle)
    does not "move" in time.  I.e. the coords of the 3 corner points of the
triangle do not change.

b) Do you mean you want a set of triangles which are like fan blades and
you want to spin them?  So that any instant
    the fan blades (triangles) are in different positions, and the
particles collide with triangles that are moving normal to their plane?
    That is something SPARTA does not currently support.  I'm also not clear
it makes sense as a model in
    the DMSC context.  Michael way want to comment on that.

Steve

**Comment by sjplimp** [comment]
@magalli - can you look at my comment/Q on this feature request ?

**Comment by stanmoore1** [comment]
@oscillatingion it sounds like your question was answered above, so  I'm closing this issue. Let us know if you have other issues.
