### ISSUE TITLE
Fix emit/surf command fails when using equals-style variable for setting particle number

### ISSUE THREAD

**Issue by ee-nn** [sparta/sparta#435]
## Summary

When using the `n` (number of particles) keyword for the `fix emit/surf` command, only hard-coded integer values will work. Any use of a variable after the keyword will cause the `Illegal fix emit/surf/normal command` error. 

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

13Apr2023

## Expected Behavior (Bug Report)

Surface or a subset of selected surface elements emit the number of particles per grid cell per time step specified in the command. According to [the manual](https://sparta.github.io/doc/Manual.pdf#page=300&zoom=100,0,48), "The Np value can be also be specified as an equal-style variable. If the value is a variable, it should be specified as v_name, where name is the variable name. In this case, the variable will be evaluated on each emission timestep, and its value used as Np on that step to determine the target number of emitted particles for each grid cell/surface element pair." 

## Actual Behavior (Bug Report)

Upon defining a variable and inserting it into the arguments of the `fix emit/surf` command with the correct `n v_name` syntax, the error `Illegal fix emit/surf/normal command` is thrown. 

## Steps to Reproduce (Bug Report)

Open the `in.emit.surf.flow` file in the `~/sparta-13Apr2023/examples/emit` directory of your SPARTA distribution, and replace the existing `fix emit/surf` command with these two lines: 

`variable testVar equal 10`
`fix in emit/surf air all perspecies no n v_testVar`

**Comment by timteichmann** [comment]
The actual issue here is that the PDF manual on the website is updated more frequently than new SPARTA versions are released. For this reason the manual describes a more recent code state than indicated on the front page where it clearly states `3 Apr 2023 version`; therefore your confusion is totally understandable. If you check your local documentation (the HTML files that came with your download) you will realize that the feature you are trying to use was actually not included in the April release (it was added to the code base on beginning of May).

The "fix" to this issue would therefore be to either change the title page of the PDF on the homepage to not specify the SPARTA version but the date at which the PDF was built from the current master or to only update said PDF together with github releases.

**Comment by stanmoore1** [comment]
@ee-nn if you update your SPARTA version, it should fix this issue. We are planning another release which will bring everything into sync again.

**Comment by stanmoore1** [comment]
@timteichmann thanks for pointing this out!
