### ISSUE TITLE
Temperature calculation error for "vibrate discrete" command

### ISSUE THREAD

**Issue by realprivate** [sparta/sparta#467]
## Summary

Errors with vibrational temperatures when using the "vibrate discrete" command

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

I am currently using SPARTA to simulate high-temperature air, treated as a mixture of O2 and N2. The "vibrate discrete" command is employed to model the vibrational relaxation process. However, for this type of two-component diatomic gas, SPARTA seems to inaccurately calculate the vibrational temperatures.

## SPARTA Version (Bug Report)

SPARTA (7 Mar 2024)

## Expected Behavior (Bug Report)

To illustrate this issue, I conducted a simple 0-D test case where the gas mixture was in thermal equilibrium. The SPARTA input files can be found in the attachment. As expected, the translational, rotational, and vibrational temperatures should be equal (Ttran = Trot = Tvib = 8000K).

## Actual Behavior (Bug Report)

According to the output dump_grid file, the temperature of O2 is correct, whereas the temperature of N2 is consistently incorrect (approximately 7500K). Furthermore, it has been observed that the calculation error in vibrational temperature occurs only for the second type of molecular species defined by the "species" command.

## Steps to Reproduce (Bug Report)

Using the SPARTA input files (see the attachment) can reproduce this bug.
[SPARTA_input.zip](https://github.com/sparta/sparta/files/15070680/SPARTA_input.zip)

**Comment by mgallis** [comment]
Can you please repeat your test at a higher temperature and see if the difference persists?
The reduced temperature may be an effect of the quantization (partially excited) of the vibrational mode.

Michael Gallis

From: Qihan Ma ***@***.***>
Date: Monday, April 22, 2024 at 8:57 PM
To: sparta/sparta ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [sparta/sparta] Temperature calculation error for "vibrate discrete" command (Issue #467)
Summary

Errors with vibrational temperatures when using the "vibrate discrete" command

Type of Issue

Bug Report

Detailed Description (Enhancement Suggestion)

I am currently using SPARTA to simulate high-temperature air, treated as a mixture of O2 and N2. The "vibrate discrete" command is employed to model the vibrational relaxation process. However, for this type of two-component diatomic gas, SPARTA seems to inaccurately calculate the vibrational temperatures.

SPARTA Version (Bug Report)

SPARTA (7 Mar 2024)

Expected Behavior (Bug Report)

To illustrate this issue, I conducted a simple 0-D test case where the gas mixture was in thermal equilibrium. The SPARTA input files can be found in the attachment. As expected, the translational, rotational, and vibrational temperatures should be equal (Ttran = Trot = Tvib = 8000K).

Actual Behavior (Bug Report)

According to the output dump_grid file, the temperature of O2 is correct, whereas the temperature of N2 is consistently incorrect (approximately 7500K). Furthermore, it has been observed that the calculation error in vibrational temperature occurs only for the second type of molecular species defined by the "species" command.

Steps to Reproduce (Bug Report)

Using the SPARTA input files (see the attachment) can reproduce this bug.
SPARTA_input.zip<https://github.com/sparta/sparta/files/15070680/SPARTA_input.zip>

**Comment by realprivate** [comment]
Dear Prof. Gallis,
        Following your advice, I tested the case at higher temperatures of 10000K, 15000K, and 20000K, but the problem persists. The temperature of N2 consistently shows a temperature error of about 500K. Additionally, I've noticed that if O2 is defined as the second species in the 'species' command, the temperature output error shifts from N2 to O2.

**Comment by aborner1** [comment]
Can you please try running on more than 1 grid cell? Try 8 (2 in each direction) and see whether the problem persists.

**Comment by aborner1** [comment]
Can confirm I can reproduce with latest master. Changing number of cells and relaxation numbers did not make a difference. Changing to variable relaxation numbers made no difference.
It already happens at time 0, so it's purely a vibrational temperature calculation artifact.

**Comment by stanmoore1** [comment]
I can reproduce this as well. The temperatures are affected by value of `# VibTemp (K)` in `air.species`

**Comment by stanmoore1** [comment]
I think the bug is on this line: https://github.com/sparta/sparta/blob/master/src/compute_tvib_grid.cpp#L406. That is always returning 0 when it should be both 0 and 1.

**Comment by stanmoore1** [comment]
Should be fixed by #468, can you confirm?

**Comment by stanmoore1** [comment]
This same bug shows up with https://github.com/sparta/sparta/blob/master/examples/vibrate/in.vibrate if you run it for long enough.

**Comment by realprivate** [comment]
> Should be fixed by #468, can you confirm?

I modified line 406 in compute_tvib_grid.cpp, and now the problem with the diatomic gas mixtures can be solved effectively.
