### ISSUE TITLE
use of surf2paraview.py code provided for visualizing sparta output files

### ISSUE THREAD

**Issue by ravirajawasthi17** [sparta/sparta#82]
I've downloaded SPARTA recently from the website sparta.sandia.gov and I've been trying to use the surf2paraview.py utility present in it. It has following two utilities-

1> visualizing the surface created (by pizza.py) in paraview.

2> visualizing the results obtained (shear stress, pressure etc.) on the surface in paraview from the corresponding sparta output file.

The first utility is working wherein I am able to visualize the surface in paraview, whereas in the second one I am not able to do it. 

Kindly help.

PS: the above script produces two files upon execution.  A pvd file which runs on paraview and a vtu support file. I am able to get the vtu file for the first case whereas unable to get it for the second case.

**Comment by stanmoore1** [comment]
@ravirajawasthi17 we are going to need more info on this issue. Do you get an error message or how are you "not able to do it"? @tjotaha is the SPARTA paraview expert. Also you would probably get a better response if you post this question on the SPARTA users mail list instead of Github, see https://sparta.sandia.gov/mail.html. Thank you.
